/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/pablo-theme.ts
 * Command: astryx theme build src/theme/pablo-theme.ts
 * Generated: 2026-08-03T21:56:47.181Z
 */

/// <reference path="./pablo.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const pabloTheme: DefinedTheme;
