/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/pablo-theme.ts
 * Command: astryx theme build src/theme/pablo-theme.ts
 * Generated: 2026-08-03T20:59:40.299Z
 */

// Generated by astryx theme build
export {};

declare module "@astryxdesign/core/Badge" {
	interface BadgeVariantMap {
		gray: true;
	}
}
